### ISSUE TITLE
is there a plan to make the whole XCL available?

### ISSUE THREAD

**Issue by raptoravis** [x157/Lyra-ActorWithAbilities#1]
is there a plan to make the whole XCL available?

**Comment by x157** [comment]
Not sure.

Originally that was my intent.  I asked Epic about releasing Lyra on GitHub or some other public repository (with access controls).

They said they want to do that, but there are both technical and legal challenges to that to overcome.

Thus in the interim, no I will not release XCL.  If Epic releases Lyra then I'll circle back and consider the decision again.

That being said, I may from time to time release snippets like this for example purposes.
